### ISSUE TITLE
1.16.5 server crashed  skinstates failed

### ISSUE THREAD

**Issue by genfar1980** [StevePlayzz/Skinned-Lanterns-Fabric#7] opened 2021-07-25 21:28 UTC
[25.07 16:22:26] [Server] [main/INFO]: Starting datagen in: /servers/src/generated/resources
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: java.lang.RuntimeException: java.nio.file.AccessDeniedException: /servers/src
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at me.shedaniel.cloth.impl.datagen.DataGeneratorHandlerImpl.run(DataGeneratorHandlerImpl.java:87)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at at.nuxnux.skinnedlanterns.data.basic.SkinnedStates.init(SkinnedStates.java:130)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at at.nuxnux.skinnedlanterns.data.SkinnedDataGen.init(SkinnedDataGen.java:20)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at at.nuxnux.skinnedlanterns.SkinnedLanterns.onInitialize(SkinnedLanterns.java:29)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at net.minecraft.server.Main.main(Main.java:92)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: Caused by: java.nio.file.AccessDeniedException: /servers/src
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at java.nio.file.Files.createDirectory(Files.java:674)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at java.nio.file.Files.createDirectories(Files.java:767)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at net.minecraft.class_2408.<init>(class_2408.java:37)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at net.minecraft.class_2403.method_10315(class_2403.java:40)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	at me.shedaniel.cloth.impl.datagen.DataGeneratorHandlerImpl.run(DataGeneratorHandlerImpl.java:85)
[25.07 16:22:26] [Server] [main/INFO]: [STDERR]: 	... 21 more
[25.07 16:22:26] [Server] [main/INFO]: [Skinned Lanterns] SkinnedStates Failed!

**Comment by In-Veritas** [comment] 2021-10-24 01:24
For some reason the mod seems to be trying to write on /home/src.
This error only happens on the server side btw.

[02:56:12] [main/INFO]: [STDERR]: java.lang.RuntimeException: java.nio.file.FileSystemException: /home/src: Read-only file system
[02:56:12] [main/INFO]: [STDERR]: at me.shedaniel.cloth.impl.datagen.DataGeneratorHandlerImpl.run(DataGeneratorHandlerImpl.java:88)
[02:56:12] [main/INFO]: [STDERR]: at at.nuxnux.skinnedlanterns.data.basic.SkinnedStates.init(SkinnedStates.java:130)
[02:56:12] [main/INFO]: [STDERR]: at at.nuxnux.skinnedlanterns.data.SkinnedDataGen.init(SkinnedDataGen.java:20)
[02:56:12] [main/INFO]: [STDERR]: at at.nuxnux.skinnedlanterns.SkinnedLanterns.onInitialize(SkinnedLanterns.java:29)
[02:56:12] [main/INFO]: [STDERR]: at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[02:56:12] [main/INFO]: [STDERR]: at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
[02:56:12] [main/INFO]: [STDERR]: at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33)
[02:56:12] [main/INFO]: [STDERR]: at net.minecraft.server.Main.main(Main.java:97)
[02:56:12] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:56:12] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[02:56:12] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:56:12] [main/INFO]: [STDERR]: at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[02:56:12] [main/INFO]: [STDERR]: at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[02:56:12] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[02:56:12] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
[02:56:12] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:56:12] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[02:56:12] [main/INFO]: [STDERR]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:56:12] [main/INFO]: [STDERR]: at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[02:56:12] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68)
[02:56:12] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114)
[02:56:12] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56)
[02:56:12] [main/INFO]: [STDERR]: Caused by: java.nio.file.FileSystemException: /home/src: Read-only file system
[02:56:12] [main/INFO]: [STDERR]: at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
[02:56:12] [main/INFO]: [STDERR]: at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[02:56:12] [main/INFO]: [STDERR]: at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[02:56:12] [main/INFO]: [STDERR]: at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:396)
[02:56:12] [main/INFO]: [STDERR]: at java.base/java.nio.file.Files.createDirectory(Files.java:694)
[02:56:12] [main/INFO]: [STDERR]: at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:801)
[02:56:12] [main/INFO]: [STDERR]: at java.base/java.nio.file.Files.createDirectories(Files.java:787)
[02:56:12] [main/INFO]: [STDERR]: at net.minecraft.class_2408.(class_2408.java:37)
[02:56:12] [main/INFO]: [STDERR]: at net.minecraft.class_2403.method_10315(class_2403.java:40)
[02:56:12] [main/INFO]: [STDERR]: at me.shedaniel.cloth.impl.datagen.DataGeneratorHandlerImpl.run(DataGeneratorHandlerImpl.java:86)
[02:56:12] [main/INFO]: [STDERR]: ... 21 more
[02:56:12] [main/INFO]: [Skinned Lanterns] SkinnedStates Failed!

**Comment by Steven-Baez** [comment] 2021-11-11 22:48
duplicate of #6

**Closed as completed by Steven-Baez** 2021-11-11 22:48 UTC
